Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12
