# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

# Disable all metrics.
Metrics:
  Enabled: false

# https://stackoverflow.com/q/4763121/
Style/Alias:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.3

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false
