language: ruby
rvm:
  - 2.4.1

script:
  - rake
  - rubocop

install:
  - gem install rubocop -v 0.55.0
  - gem install rest-client

notifications:
  webhooks:
    urls:
      - https://travis.discordspark.com?id=437401774236762121
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
